<?php
// Now include header.php (which includes navbar.php) at the top
$page_title = "Request Document";
include('includes/header.php');

// Enable error reporting for debugging
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

// Ensure the user is a student
if (!isset($_SESSION['user_id']) || $_SESSION['role'] !== 'student') {
    $_SESSION['alert'] = ['message' => 'Please log in as a student to request a document.', 'type' => 'danger'];
    header('Location: index.php');
    exit;
}

// Initialize variables for form feedback
$success_message = '';
$error_message = '';

// Handle form submission
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $user_id = $_SESSION['user_id'];
    $document_type = $_POST['document_type'] ?? '';
    $remarks = $_POST['remarks'] ?? '';
    $file_path = null;

    // Validate required fields
    if (empty($document_type) || empty($remarks)) {
        $error_message = 'Please fill in all required fields.';
    } else {
        // Fetch document details (price and form_needed)
        $stmt = $conn->prepare("SELECT price, form_needed FROM documents WHERE name = ? AND is_active = 1");
        $stmt->bind_param("s", $document_type);
        $stmt->execute();
        $document = $stmt->get_result()->fetch_assoc();
        $price = $document['price'] ?? 0.00;
        $form_needed = $document['form_needed'] ?? 0;
        $stmt->close();

        // Handle file upload if form is needed
        if ($form_needed && isset($_FILES['form_file']) && $_FILES['form_file']['error'] === UPLOAD_ERR_OK) {
            $upload_dir = 'uploads/forms/';
            if (!is_dir($upload_dir)) {
                mkdir($upload_dir, 0755, true);
            }

            $file_name = uniqid() . '-' . basename($_FILES['form_file']['name']);
            $file_path = $upload_dir . $file_name;

            if (!move_uploaded_file($_FILES['form_file']['tmp_name'], $file_path)) {
                $error_message = 'Failed to upload the form. Please try again.';
            }
        } elseif ($form_needed) {
            $error_message = 'Please upload the required form.';
        }

        // If no errors, proceed with inserting the request
        if (empty($error_message)) {
            // Insert the request (id will be auto-generated by the database)
            $stmt = $conn->prepare("INSERT INTO requests (user_id, document_type, price, status, remarks, file_path, requested_date, created_at) VALUES (?, ?, ?, 'Pending', ?, ?, NOW(), NOW())");
            $stmt->bind_param("isdss", $user_id, $document_type, $price, $remarks, $file_path);
            if ($stmt->execute()) {
                $stmt->close(); // Close the statement for the requests insert

                // Create a notification for the student
                $message = "Your document request for '$document_type' has been submitted.";
                $link = "dashboard.php";
                $stmt_notification = $conn->prepare("INSERT INTO notifications (user_id, message, link, is_read, created_at) VALUES (?, ?, ?, 0, NOW())");
                $stmt_notification->bind_param("iss", $user_id, $message, $link);
                $stmt_notification->execute();
                $stmt_notification->close(); // Close the statement for the notifications insert

                // Set success message
                $success_message = 'Document request submitted successfully! You can view it on your dashboard.';
                // Reset form fields by clearing POST data
                $_POST = [];
            } else {
                $error_message = 'Failed to submit request. Please try again.';
                error_log("Failed to insert request: " . $stmt->error);
                $stmt->close(); // Close the statement in case of failure
            }
        }
    }
}

// Fetch available documents
$stmt = $conn->prepare("SELECT * FROM documents WHERE is_active = 1");
$stmt->execute();
$documents = $stmt->get_result()->fetch_all(MYSQLI_ASSOC);
$stmt->close();
?>

<link rel="stylesheet" href="../assets/css/user_dashboard.css">
<link rel="stylesheet" href="../assets/css/request.css">

<main>
    <?php alertMessage(); ?>

    <div class="page-header">
        <h1>Request a Document</h1>
        <small>Hello, <?= htmlspecialchars($user['firstname'] ?? 'User'); ?>! Here you can request a document.</small>
    </div>
    <div class="page-content">
        <h5 class="page-title mb-4">Document Request Form</h5>
        <form method="POST" enctype="multipart/form-data">
            <div class="mb-3">
                <label for="document_type" class="form-label">Document Type</label>
                <select name="document_type" id="document_type" class="form-select" required>
                    <option value="" disabled selected>Select Document</option>
                    <?php foreach ($documents as $doc): ?>
                        <option value="<?= htmlspecialchars($doc['name']); ?>" data-form-needed="<?= $doc['form_needed']; ?>" <?= isset($_POST['document_type']) && $_POST['document_type'] === $doc['name'] ? 'selected' : ''; ?>>
                            <?= htmlspecialchars($doc['name']); ?> (₱<?= htmlspecialchars($doc['price']); ?>)
                        </option>
                    <?php endforeach; ?>
                </select>
            </div>
            <div class="mb-3" id="form_upload" style="display: none;">
                <label for="form_file" class="form-label">Upload Required Form</label>
                <input type="file" name="form_file" id="form_file" class="form-control" accept=".pdf,.doc,.docx">
                <small class="form-text text-muted">Accepted formats: PDF, DOC, DOCX (Max 5MB)</small>
            </div>
            <div class="mb-3">
                <label for="remarks" class="form-label">Purpose/Remarks</label>
                <textarea name="remarks" id="remarks" class="form-control" rows="4" required placeholder="Enter the purpose of your request..."><?= isset($_POST['remarks']) ? htmlspecialchars($_POST['remarks']) : ''; ?></textarea>
            </div>
            <button type="submit" class="btn btn-primary">Submit Request</button>
            <a href="dashboard.php" class="btn btn-secondary">Back to Dashboard</a>
        </form>
    </div>
</main>

<script>
    // Show/hide form upload field based on document selection
    document.addEventListener('DOMContentLoaded', function() {
        const documentSelect = document.getElementById('document_type');
        const formUpload = document.getElementById('form_upload');

        // Set initial state based on selected option (if form was submitted with errors)
        const selectedOption = documentSelect.options[documentSelect.selectedIndex];
        const formNeeded = selectedOption.getAttribute('data-form-needed') === '1';
        formUpload.style.display = formNeeded ? 'block' : 'none';

        documentSelect.addEventListener('change', function() {
            const selectedOption = documentSelect.options[documentSelect.selectedIndex];
            const formNeeded = selectedOption.getAttribute('data-form-needed') === '1';
            formUpload.style.display = formNeeded ? 'block' : 'none';
            // Make the file input required only if form is needed
            const fileInput = document.getElementById('form_file');
            fileInput.required = formNeeded;
        });
    });
</script>

<?php include('includes/footer.php'); ?>